
linters-settings:
  cyclop:
    max-complexity: 30
  wsl:
    allow-cuddle-declarations: true
    allow-assign-and-anything: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - deadcode
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goheader
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace

  # To be enabled soon:
  # - gochecknoinits
  # - promlinter
  # - noctx

  # Explicitly disabled
  # - nlreturn

