#!/bin/sh

set -eu

export GOBIN=$PWD/bin
export PATH=$GOBIN:$PATH

if [ `which protoc-gen-go 2>/dev/null` == "" ] ; then
    echo "try: go install github.com/golang/protobuf/protoc-gen-go"
    exit 1
fi

go generate ./...
